Updates mongodb dependency to silence warning about BSON
Dependency is out, and causes a warning on 4.8.x, this silences:

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version